// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twoldpyahnzvhpfuzfkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3b2xkcHlhaG56dmhwZnV6Zmt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4ODQ0MDgsImV4cCI6MjA2MzQ2MDQwOH0.GRIwE4VI9gQWr-ve4WtIcPbdpmxkgJZVysm6tBZy7rM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);